boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 9f1801dc-7a8c-4969-a97f-c0432a3a4331
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
check/check-0.9.13.tar.gz:
  size: 752880
  object_id: d6c51160-8a67-4290-a337-dbc9d515d08a
  sha: 09f682d2239b1353818b74d06099a17460450240
cipher_finder/cipher_finder.jar:
  size: 22062037
  object_id: 814c01f1-ba14-4f94-46d2-66838551293d
  sha: f5697d957fdc71e32b1e421594e084c0c3c7aea2
cli/cf-cli_6.36.1_linux_x86-64.tgz:
  size: 5910456
  object_id: 3cea6e9c-e3ed-40f2-7929-c07a0ed77149
  sha: faade069c0e7a76cb3bb1c9dfd69da2d340155c9
galera/galera-25.3.23.tar.gz:
  size: 3338538
  object_id: 90c147fb-a02a-45c7-5036-2dee134223ac
  sha: 000e20ad02113e796a8a551a2733674338fbbc92
golang/go1.9.6.linux-amd64.tar.gz:
  size: 118279574
  object_id: e45655dc-c876-4236-7f93-d9b5522d1e0f
  sha: 012c86a6b555272fe36fb9cdb45082ffc5ea5c7c
mariadb/mariadb-10.1.32.tar.gz:
  size: 68001321
  object_id: 2bfe222d-4f57-493c-400b-299727b94bac
  sha: c315c5054612647c3665d286910d9f33c5c61ce3
mysqlclient/mariadb-connector-c-2.1.0-src.tar.gz:
  size: 1912888
  object_id: e1e0446a-8cbd-4b8e-b496-fc20f530fd7c
  sha: 2fea886fd8ddf3e17d6228d282828afeaee0a317
pcre-8.35.tar.gz:
  size: 1996552
  object_id: 34f25eac-2566-45c5-afee-babae9b83f63
  sha: 5a0efc7332c6741114372020a60acfed22befcb9
python/Python-2.7.13.tgz:
  size: 17076672
  object_id: d97aea2b-8036-4b6a-709c-200865a69da1
  sha: dce2b862a30099ee48c19a7c34e2d7c2eeff5670
ruby/bundler-1.16.1.gem:
  size: 349696
  object_id: 8a15e71c-4392-4566-7a4e-56b4d18f4493
  sha: bca8cd6a0d44524c55a04256307da33e6fe37d5f
ruby/ruby-2.3.5.tar.gz:
  size: 17836997
  object_id: 821e39bd-4996-428b-4d5d-50d69cf58743
  sha: 3247e217d6745c27ef23bdc77b6abdb4b57a118f
ruby/rubygems-2.6.14.tgz:
  size: 769418
  object_id: 7c11fe2a-3f49-42b3-522f-458b7ec1fb5c
  sha: d9c131e7b84fbe9179033545ffddc4097e9c6c7b
ruby/yaml-0.1.7.tar.gz:
  size: 527518
  object_id: 4f10a1e8-949e-4d9b-6e49-fabe5cba6fc0
  sha: 3590cbf092ef4c71bc0a9b404c00a626b1e04dee
scons/scons-2.3.1.tar.gz:
  size: 499037
  object_id: e3136aa7-9bf6-4c49-a26d-9ebe85665818
  sha: 775e715e49fe5fd8e1d29551a296fdc9267509e7
xtrabackup/autoconf-2.65.tar.gz:
  size: 1738880
  object_id: 12402e0c-14bd-4a31-8344-858c09639f67
  sha: ae9e1ab046822007f25c88e1d8f2166e065da8c2
xtrabackup/automake-1.14.1.tar.gz:
  size: 2240681
  object_id: 22110fae-0404-48d2-a2a0-869b40172c09
  sha: 0bb1714b78d70cab9907d2013082978a28f48a46
xtrabackup/libaio_0.3.110.orig.tar.gz:
  size: 42270
  object_id: 10d3be70-6c51-4220-9d46-8de75281fd3d
  sha: f8f6ed15f22e528f6f415939b07854539e3360e4
xtrabackup/libev-4.22.tar.gz:
  size: 530094
  object_id: 023ba1e4-a21c-44f8-8c7d-51933bb0a3c9
  sha: b5cc3f6d8d842e23fccc9b27d318ae7fa3d3bf60
xtrabackup/libtool-2.4.2.tar.gz:
  size: 2632347
  object_id: 958f3335-2373-4c4f-9db1-7391a9a7e6f2
  sha: 22b71a8b5ce3ad86e1094e7285981cae10e6ff88
xtrabackup/percona-xtrabackup-2.4.8.tar.gz:
  size: 57965576
  object_id: ca08f6b1-14a5-45f7-4e57-df362b2fcb8a
  sha: 5cc6b689b9682923211f9aace7ec6c6d22b69346
xtrabackup/socat-1.7.3.2.tar.gz:
  size: 611707
  object_id: ba6cfda8-0c00-451e-6338-2007ef503d56
  sha: 28eca1f8efeadde3f96c1ac89e553c28d736d41d
