boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 9f1801dc-7a8c-4969-a97f-c0432a3a4331
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
check/check-0.9.13.tar.gz:
  size: 752880
  object_id: d6c51160-8a67-4290-a337-dbc9d515d08a
  sha: 09f682d2239b1353818b74d06099a17460450240
cipher_finder/cipher_finder.jar:
  size: 22010074
  object_id: bc8eb575-27d5-462e-422e-6e91e790b3b1
  sha: c5e206b44b01a98f2b9af8cc9318c2c43cea2b97
cli/cf-cli_6.32.0_linux_x86-64.tgz:
  size: 6065317
  object_id: 1d0c8a45-f1d8-4d53-40fe-f21a177cd03a
  sha: ad4dd01db5e6498bd38583d73c75480c700e1b5f
galera/galera-25.3.20.tar.gz:
  size: 3322846
  object_id: 5a3df186-0126-40d6-4bde-3aa7528646f1
  sha: 350bb947ecb40f47186da6e50b3453d29db7d68e
golang/go1.8.3.linux-amd64.tar.gz:
  size: 90029041
  object_id: a9a0aa90-83c2-40dc-499b-7b5d33918fdd
  sha: 838c415896ef5ecd395dfabde5e7e6f8ac943c8e
mariadb/mariadb-10.1.26.tar.gz:
  size: 61887132
  object_id: b5329ed2-3834-413f-42dd-1d9948ffb6db
  sha: 464a257a6ace60213d59f794f8bdbf2a03752306
mysqlclient/mariadb-connector-c-2.1.0-src.tar.gz:
  size: 1912888
  object_id: e1e0446a-8cbd-4b8e-b496-fc20f530fd7c
  sha: 2fea886fd8ddf3e17d6228d282828afeaee0a317
pcre-8.35.tar.gz:
  size: 1996552
  object_id: 34f25eac-2566-45c5-afee-babae9b83f63
  sha: 5a0efc7332c6741114372020a60acfed22befcb9
python/Python-2.7.13.tgz:
  size: 17076672
  object_id: d97aea2b-8036-4b6a-709c-200865a69da1
  sha: dce2b862a30099ee48c19a7c34e2d7c2eeff5670
ruby/bundler-1.12.5.gem:
  size: 280064
  object_id: 6aa476be-2c24-43db-a409-3ad7828164b1
  sha: a414b2aafa54affac99dc453ced5adc152211eb9
ruby/ruby-2.3.1.tar.gz:
  size: 17797997
  object_id: ba97d279-69da-4802-b142-83a4c6853bc2
  sha: c39b4001f7acb4e334cb60a0f4df72d434bef711
ruby/rubygems-2.6.13.tgz:
  size: 768906
  object_id: b3209093-5aa7-4381-45da-f2f644cf749d
  sha: ebc88822f50656e84ec87687029e9baf5b895f63
ruby/yaml-0.1.6.tar.gz:
  size: 503012
  object_id: 566e2377-6c7b-4c24-8757-60efb86da513
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
scons/scons-2.3.1.tar.gz:
  size: 499037
  object_id: e3136aa7-9bf6-4c49-a26d-9ebe85665818
  sha: 775e715e49fe5fd8e1d29551a296fdc9267509e7
xtrabackup/autoconf-2.65.tar.gz:
  size: 1738880
  object_id: 12402e0c-14bd-4a31-8344-858c09639f67
  sha: ae9e1ab046822007f25c88e1d8f2166e065da8c2
xtrabackup/automake-1.14.1.tar.gz:
  size: 2240681
  object_id: 22110fae-0404-48d2-a2a0-869b40172c09
  sha: 0bb1714b78d70cab9907d2013082978a28f48a46
xtrabackup/libaio_0.3.110.orig.tar.gz:
  size: 42270
  object_id: 10d3be70-6c51-4220-9d46-8de75281fd3d
  sha: f8f6ed15f22e528f6f415939b07854539e3360e4
xtrabackup/libev-4.22.tar.gz:
  size: 530094
  object_id: 023ba1e4-a21c-44f8-8c7d-51933bb0a3c9
  sha: b5cc3f6d8d842e23fccc9b27d318ae7fa3d3bf60
xtrabackup/libtool-2.4.2.tar.gz:
  size: 2632347
  object_id: 958f3335-2373-4c4f-9db1-7391a9a7e6f2
  sha: 22b71a8b5ce3ad86e1094e7285981cae10e6ff88
xtrabackup/percona-xtrabackup-percona-xtrabackup-2.4.5.tar.gz:
  size: 51954652
  object_id: 54fc2860-5858-4c85-b110-3b37633676cb
  sha: 8f86039fa330739e1a6be77dcbd2274498e090bf
xtrabackup/socat-1.7.3.1.tar.gz:
  size: 606049
  object_id: e70cc852-c9b3-4e69-8b67-0badc7cacaaf
  sha: a6f1d8ab3e85f565dbe172f33a9be6708dd52ffb
