---
ruby/bundler-1.3.5.gem:
  object_id: 7eba9228-785f-42b7-8315-9fe10f04e249
  sha: 2cad3052a59b83f1f616e8202f5c714e46bd8523
  size: 268800
ruby/rubygems-2.1.11.tgz:
  object_id: 05612435-f24d-4416-9c49-3897c4d5fa0b
  sha: ca3033432cae28deb7ced79cda271cb292b70e59
  size: 367166
ruby/yaml-0.1.5.tar.gz:
  object_id: da3ee2c1-11f0-4969-a37f-0298f8bf8987
  sha: 8b78cb9f759c7d80db8a7328c0ebecfe34fde737
  size: 504897
boost/boost_1_55_0.tar.gz:
  object_id: 52348346-ba79-41e1-9c71-74ee464570d6
  sha: 61ed0e57d3c7c8985805bb0682de3f4c65f4b6e5
  size: 69481257
scons/scons-2.3.1.tar.gz:
  object_id: e3136aa7-9bf6-4c49-a26d-9ebe85665818
  sha: 775e715e49fe5fd8e1d29551a296fdc9267509e7
  size: 499037
check/check-0.9.13.tar.gz:
  object_id: d6c51160-8a67-4290-a337-dbc9d515d08a
  sha: 09f682d2239b1353818b74d06099a17460450240
  size: 752880
pcre-8.35.tar.gz:
  object_id: 34f25eac-2566-45c5-afee-babae9b83f63
  sha: 5a0efc7332c6741114372020a60acfed22befcb9
  size: 1996552
python/Python-2.7.8.tgz:
  object_id: f9c52077-dfa2-4f9a-80d4-46e3b22adf51
  sha: 511960dd78451a06c9df76509635aeec05b2051a
  size: 14846119
xtrabackup/autoconf-2.65.tar.gz:
  object_id: 12402e0c-14bd-4a31-8344-858c09639f67
  sha: ae9e1ab046822007f25c88e1d8f2166e065da8c2
  size: 1738880
xtrabackup/automake-1.14.1.tar.gz:
  object_id: 22110fae-0404-48d2-a2a0-869b40172c09
  sha: 0bb1714b78d70cab9907d2013082978a28f48a46
  size: 2240681
xtrabackup/libaio_0.3.110.orig.tar.gz:
  object_id: 10d3be70-6c51-4220-9d46-8de75281fd3d
  sha: f8f6ed15f22e528f6f415939b07854539e3360e4
  size: 42270
xtrabackup/libdbd-mysql-perl_4.025.orig.tar.gz:
  object_id: 4013014b-5261-4fea-915f-d7f08c3b3733
  sha: 7c148d347988785239973835f8b5a8b78677ae47
  size: 135538
xtrabackup/libdbi-perl_1.630.orig.tar.gz:
  object_id: 2c9e9439-ef0d-400e-a79c-d608c04ef8c3
  sha: 8e8ca6484a3e0c7f4e268e46101faed576e072fc
  size: 588554
xtrabackup/libtool-2.4.2.tar.gz:
  object_id: 958f3335-2373-4c4f-9db1-7391a9a7e6f2
  sha: 22b71a8b5ce3ad86e1094e7285981cae10e6ff88
  size: 2632347
xtrabackup/socat-1.7.2.4.tar.gz:
  object_id: cd877813-c9ac-4596-b4e4-d361fe5bbdb6
  sha: c33904b83295accef2aaff8adf7eedd3310f9777
  size: 583762
ruby/ruby-2.1.4.tar.gz:
  object_id: 487424bc-4b2f-4474-8eb3-dfe8c62f57f2
  sha: 29e9cfdd9e989b7621d7696ef3f970262a08dbc3
  size: 15127418
ruby/ruby-2.1.5.tar.gz:
  object_id: fe2793ce-982c-4934-8e72-144236f2824b
  sha: 9c0a238bd7839a4b51871641945a3da90997b8c2
  size: 15127433
golang/go1.4.2.linux-amd64.tar.gz:
  object_id: 2f024dbf-1a20-4bec-a62a-adaf5e202459
  sha: 5020af94b52b65cc9b6f11d50a67e4bae07b0aff
  size: 62442704
cli/cf-linux-amd64-6.10.0.tgz:
  object_id: adb9d3ea-3582-4ff3-a3b4-eab569915e16
  sha: f845800310e4b702a39a2f1191e3d71862630103
  size: 4803309
galera/galera-25.3.9-src.tar.gz:
  object_id: 9f0e7032-1b75-4794-bf8c-e31863a82120
  sha: 896c7ea57781e70a5cf02c919dc3dd93968cb488
  size: 2949775
xtrabackup/percona-xtrabackup-percona-xtrabackup-2.2.10.tar.gz:
  object_id: a195ae63-042e-448d-9020-b2dc1bd5b661
  sha: e93d34bc0ef6bc06bf356523c11c9906a079fd8f
  size: 33248338
mysqlclient/mariadb-connector-c-2.1.0-src.tar.gz:
  object_id: e1e0446a-8cbd-4b8e-b496-fc20f530fd7c
  sha: 2fea886fd8ddf3e17d6228d282828afeaee0a317
  size: 1912888
mariadb/mariadb-galera-10.0.19.tar.gz:
  object_id: 86040e96-82ce-47e2-8003-1b646ef5e9e8
  sha: 15fc7f3799f816345fd771eeb229f630a12fdabc
  size: 56520261
